Improved pearl processing.

diff --git a/ecommerce/pricing/Makefile b/ecommerce/pricing/Makefile
--- a/ecommerce/pricing/Makefile
+++ b/ecommerce/pricing/Makefile
@@ -8,11 +8,28 @@ MUTANT_TARGET_DIRS := lib
 
 mutate:
 ifeq ($(origin MUTANT_NODE_INDEX), environment)
-	@echo "Running mutation tests in parallel (Node $(MUTANT_NODE_INDEX)/$(MUTANT_TOTAL_NODES)) for pricing, using .mutant.yml"
-	@find $(MUTANT_TARGET_DIRS) -path ./vendor -prune -o -name '*.rb' -print | sed 's|^\./||' > .all_files.tmp
+	@echo "Running mutation tests in parallel (Node $$(( $(MUTANT_NODE_INDEX) + 1 ))/$(MUTANT_TOTAL_NODES)) for pricing"
+	@echo "--- DEBUG: Finding potential subject files ---"
+	@find $(MUTANT_TARGET_DIRS) -path ./vendor -prune -o -name '*.rb' -print > .all_files.tmp
+	@echo "--- DEBUG: Found files count: $(shell wc -l < .all_files.tmp)"
+	@echo "--- END DEBUG ---"
 	@awk "NR % $(MUTANT_TOTAL_NODES) == $(MUTANT_NODE_INDEX)" .all_files.tmp > .node_files.tmp
-	@SUBJECT_NAMES_CMD="cat .node_files.tmp | perl -pe 's|^lib/||; s|\\.rb$$||; s|/|::|g; s/\\b(\\w)/ucfirst(\$1)/ge'"
-	@SUBJECT_ARGS=$$($$SUBJECT_NAMES_CMD | tr '\\n' ' '); \
+	@echo "--- DEBUG: Files count for this node ($(MUTANT_NODE_INDEX)): $(shell wc -l < .node_files.tmp)"
+	@echo "--- END DEBUG ---"
+	@SUBJECT_NAMES_CMD="cat .node_files.tmp | perl -pe 's|^lib/||; s|\\.rb$$||; s|_([a-z])|uc(\$1)|eg; s|/|::|g; s/(?:^|::)(.)/\\u\$1/g'"
+	@echo "--- DEBUG: Attempting to derive subject names for this node... ---"
+	@DERIVED_NAMES=$$(eval $$SUBJECT_NAMES_CMD); \
+	 EXIT_CODE=$$?; \
+	 if [ $$EXIT_CODE -ne 0 ]; then \
+	   echo "Perl command failed with exit code $$EXIT_CODE"; \
+	   exit $$EXIT_CODE; \
+	 elif [ -z "$$DERIVED_NAMES" ]; then \
+	   echo "Perl command produced no output."; \
+	 else \
+	   echo "$$DERIVED_NAMES"; \
+	 fi
+	@echo "--- END DEBUG ---"
+	@SUBJECT_ARGS=$$(echo "$$DERIVED_NAMES" | tr '\\n' ' '); \
 	 if [ -z "$$SUBJECT_ARGS" ]; then \
 	   echo "No subjects derived for this node. Skipping."; \
 	 else \
@@ -21,7 +38,7 @@ ifeq ($(origin MUTANT_NODE_INDEX), environment)
 	 fi
 	@rm -f .all_files.tmp .node_files.tmp
 else
-	@echo "Running mutation tests locally (using .mutant.yml)"
+	@echo "Running mutation tests locally for pricing (using .mutant.yml)"
 	@RAILS_ENV=test bundle exec mutant run
 endif
 
diff --git a/rails_application/Makefile b/rails_application/Makefile
--- a/rails_application/Makefile
+++ b/rails_application/Makefile
@@ -27,18 +27,25 @@ ifeq ($(origin MUTANT_NODE_INDEX), environment)
 		-not -path 'db/*' \
 		-not -path 'vendor/*' \
 		-print > .all_files.tmp
-	@echo "--- DEBUG: Found files (.all_files.tmp): ---"
-	@cat .all_files.tmp || echo "No files found by find."
+	@echo "--- DEBUG: Found files count: $(shell wc -l < .all_files.tmp)"
 	@echo "--- END DEBUG ---"
 	@awk "NR % $(MUTANT_TOTAL_NODES) == $(MUTANT_NODE_INDEX)" .all_files.tmp > .node_files.tmp
-	@echo "--- DEBUG: Files for this node ($(MUTANT_NODE_INDEX)) (.node_files.tmp): ---"
-	@cat .node_files.tmp || echo "No files selected for this node by awk."
+	@echo "--- DEBUG: Files count for this node ($(MUTANT_NODE_INDEX)): $(shell wc -l < .node_files.tmp)"
 	@echo "--- END DEBUG ---"
-	@SUBJECT_NAMES_CMD="cat .node_files.tmp | perl -pe 's|^(app|lib)/||; s|\\.rb$$||; s|/|::|g; s/\\b(\\w)/ucfirst(\$1)/ge'"
-	@echo "--- DEBUG: Derived subject names for this node: ---"
-	@eval $$SUBJECT_NAMES_CMD || echo "Perl command failed or produced no output."
+	@SUBJECT_NAMES_CMD="cat .node_files.tmp | perl -pe 's|^(app|lib)/||; s|\\.rb$$||; s|_([a-z])|uc(\$1)|eg; s|/|::|g; s/(?:^|::)(.)/\\u\$1/g'"
+	@echo "--- DEBUG: Attempting to derive subject names for this node... ---"
+	@DERIVED_NAMES=$$(eval $$SUBJECT_NAMES_CMD); \
+	 EXIT_CODE=$$?; \
+	 if [ $$EXIT_CODE -ne 0 ]; then \
+	   echo "Perl command failed with exit code $$EXIT_CODE"; \
+	   exit $$EXIT_CODE; \
+	 elif [ -z "$$DERIVED_NAMES" ]; then \
+	   echo "Perl command produced no output."; \
+	 else \
+	   echo "$$DERIVED_NAMES"; \
+	 fi
 	@echo "--- END DEBUG ---"
-	@SUBJECT_ARGS=$$($$SUBJECT_NAMES_CMD | tr '\\n' ' '); \
+	@SUBJECT_ARGS=$$(echo "$$DERIVED_NAMES" | tr '\\n' ' '); \
 	 if [ -z "$$SUBJECT_ARGS" ]; then \
 	   echo "No subjects derived for this node. Skipping."; \
 	 else \
